### ISSUE TITLE
package in Docker

### ISSUE THREAD

**Issue by er1z** [StalkR/dns-reverse-proxy#10]
Been playing with this project and it really solved my problem, thanks.

I want to share my Docker setup:
```
FROM golang:1-alpine

RUN apk add --no-cache git \
    && go get -u github.com/miekg/dns \
    && go get -u github.com/StalkR/dns-reverse-proxy

EXPOSE 53

CMD dns-reverse-proxy
```

And called within compose:
```
version: "2.4"
services:
   proxy:
      build: proxy/
      command: dns-reverse-proxy -default 192.168.1.1:53 -route .example.org.=172.16.0.2:53
```

This image could be also shared on Docker Hub (of course, after needed tweaks).
